fragment ToolParts on Tool {
  __typename
  name
  description
  category
  subcategory
  icon
  url
  tags
  devices
  display
  status
  featured
  body
  notes
  previouslyUsed
  replacedBy
  startedUsing
  dateAdded
}
