backend:
  name: github
  repo: amlfi/tech-stack
  branch: main
  base_url: https://api.netlify.com # For GitHub OAuth
  auth_endpoint: auth

# Uncomment for local development
# local_backend: true

media_folder: "src/images/tools" # Where uploaded images will be stored
public_folder: "/images/tools" # Public URL path for images

collections:
  - name: "tools"
    label: "Tools"
    folder: "content/tools"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Tool Name", name: "name", widget: "string" }
      - { label: "Category", name: "category", widget: "string", hint: "e.g., development, design, productivity" }
      - { label: "Subcategory", name: "subcategory", widget: "string", hint: "Optional: e.g., code-editors, design-tools", required: false }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Website URL", name: "url", widget: "string", required: false }
      - { label: "Icon/Logo", name: "icon", widget: "image", required: false }
      - label: "Devices"
        name: "devices"
        widget: "select"
        multiple: true
        options: ["mbp", "studio", "ios"]
        hint: "Which devices do you use this on?"
        required: false
      - label: "Tags"
        name: "tags"
        widget: "list"
        required: false
        field: { label: "Tag", name: "tag", widget: "string" }
      - { label: "Display on Site", name: "display", widget: "boolean", default: true, hint: "Show this app on the site?" }
      - { label: "Featured", name: "featured", widget: "boolean", default: false, required: false }
      - { label: "Status", name: "status", widget: "select", options: ["active", "retired"], default: "active", required: false }
      - { label: "Previously Used", name: "previouslyUsed", widget: "string", hint: "What tool did you use before this one?", required: false }
      - { label: "Replaced By", name: "replacedBy", widget: "string", hint: "If retired, what tool replaced this?", required: false }
      - { label: "Why I Use It", name: "body", widget: "markdown", required: false }
      - { label: "Extended Notes", name: "notes", widget: "markdown", hint: "Additional details shown in modal", required: false }

  - name: "categories"
    label: "Categories"
    file: "content/categories.json"
    fields:
      - label: "Categories"
        name: "categories"
        widget: "list"
        fields:
          - { label: "ID", name: "id", widget: "string" }
          - { label: "Name", name: "name", widget: "string" }
          - { label: "Icon", name: "icon", widget: "string" }
          - { label: "Description", name: "description", widget: "text", required: false }
          - { label: "Order", name: "order", widget: "number", default: 0 }

  - name: "settings"
    label: "Site Settings"
    file: "content/settings.json"
    fields:
      - { label: "Site Title", name: "title", widget: "string" }
      - { label: "Site Description", name: "description", widget: "text" }
      - { label: "Site URL", name: "url", widget: "string" }
      - { label: "Author Name", name: "author", widget: "string" }
      - { label: "GitHub URL", name: "github", widget: "string", required: false }
      - { label: "Twitter URL", name: "twitter", widget: "string", required: false }
      - { label: "LinkedIn URL", name: "linkedin", widget: "string", required: false }
      - label: "Theme"
        name: "theme"
        widget: "select"
        options: ["light", "dark", "auto"]
        default: "auto"
