# Decap CMS Configuration for Tech Stack

backend:
  name: github
  repo: amlfi/tech-stack
  branch: main

# Publish mode: editorial workflow allows drafts, reviews, and approvals
publish_mode: editorial_workflow

# Media files configuration
media_folder: "src/images/tools" # Where uploaded images are saved
public_folder: "./images/tools" # Path used in generated HTML

# Collections define the content structure
collections:
  # Tools Collection
  - name: "tools"
    label: "Tools"
    folder: "content/tools"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - {
          label: "Category",
          name: "category",
          widget: "select",
          options: ["development", "design", "productivity", "infrastructure", "collaboration", "other"]
        }
      - { label: "Subcategory", name: "subcategory", widget: "string", required: false }
      - { label: "Icon", name: "icon", widget: "image", required: false }
      - { label: "URL", name: "url", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - {
          label: "Status",
          name: "status",
          widget: "select",
          options: ["active", "retired"],
          default: "active"
        }
      - { label: "Featured", name: "featured", widget: "boolean", default: false, required: false }
      - { label: "Content (Why I Use It)", name: "content", widget: "markdown", required: false }
      - { label: "Notes", name: "notes", widget: "markdown", required: false }
      - { label: "Previously Used", name: "previouslyUsed", widget: "string", required: false }
      - { label: "Replaced By", name: "replacedBy", widget: "string", required: false }

  # Categories Collection (single file)
  - name: "categories"
    label: "Categories"
    files:
      - label: "All Categories"
        name: "categories"
        file: "content/categories.json"
        fields:
          - label: "Categories"
            name: "categories"
            widget: "list"
            fields:
              - { label: "ID", name: "id", widget: "string" }
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Icon", name: "icon", widget: "string" }
              - { label: "Order", name: "order", widget: "number", default: 0 }

  # Site Configuration
  - name: "config"
    label: "Site Configuration"
    files:
      - label: "Site Settings"
        name: "site"
        file: "content/settings.json"
        fields:
          - { label: "Site Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "URL", name: "url", widget: "string" }
          - { label: "Author", name: "author", widget: "string" }
